/**
 * agentergonomics.org — minimalist white static site generator.
 * Screens the benchmark subjects → benchmark.json + a prerendered index +
 * per-subject report pages. Static (fastest load) → host on Cloudflare Pages
 * (output dir = site/). Re-run to publish new results.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { screen } from "../core/workflow.ts";
import { designFixes } from "../core/designer.ts";
import { SURFACES, LENSES, SURFACE_LABEL, LENS_LABEL, cellId } from "../core/model.ts";
import type { Profile } from "../core/profile.ts";

const OOTA = "/Users/shinyobjectz/Apps/shinyobjectz/projects/out-of-thin-air";
const KINDS = [
  { id: "harness", label: "Harnesses" },
  { id: "skill", label: "Skills" },
  { id: "sdk", label: "SDKs" },
  { id: "tool", label: "Tools" },
  { id: "system", label: "Systems" },
];

const esc = (s: any) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const safe = (s: string) => s.replace(/[^a-z0-9._-]/gi, "_");
const fmt = (v: number | null | undefined) => (v == null ? "·" : (v >= 0 ? "+" : "") + v.toFixed(2));

/** monochrome cell: light grey fill ∝ goodness; hostile = outlined+bold. */
function cellStyle(v: number | null | undefined): string {
  if (v == null) return "color:#bbb";
  if (v <= -0.5) return "box-shadow:inset 0 0 0 2px #111;font-weight:700";
  const L = 100 - Math.round(((v + 1) / 2) * 22); // 89%..100%
  return `background:hsl(0 0% ${L}%)`;
}

const CSS = `
*{box-sizing:border-box}
html{font:15px/1.55 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#111;background:#fff}
body{margin:0;max-width:1040px;padding:48px 24px 96px;margin-inline:auto}
a{color:#111;text-decoration:none;border-bottom:1px solid #ddd}
a:hover{border-color:#111}
h1{font-size:22px;font-weight:600;letter-spacing:-.02em;margin:0 0 4px}
h2{font-size:14px;font-weight:600;text-transform:uppercase;letter-spacing:.08em;color:#888;margin:40px 0 12px}
.sub{color:#888;margin:0 0 28px;font-size:14px}
.tabs{display:flex;gap:4px;margin:0 0 20px;flex-wrap:wrap}
.tab{padding:6px 12px;border:1px solid #eee;border-radius:999px;cursor:pointer;font-size:13px;color:#888;background:#fff}
.tab.on{border-color:#111;color:#111}
.tab .n{color:#bbb;margin-left:6px}
input.q{width:100%;padding:9px 12px;border:1px solid #eee;border-radius:8px;font:inherit;margin:0 0 16px}
table{border-collapse:collapse;width:100%;font-size:13px}
th,td{text-align:left;padding:7px 9px;border-bottom:1px solid #f1f1f1;white-space:nowrap}
th{color:#888;font-weight:500;cursor:pointer;user-select:none}
td.n{font-variant-numeric:tabular-nums;text-align:right}
.cell{display:inline-block;min-width:46px;text-align:right;padding:2px 7px;border-radius:5px;font-variant-numeric:tabular-nums}
.muted{color:#888}.tiny{font-size:12px;color:#aaa}
.flag{color:#111;font-weight:700}
footer{margin-top:64px;color:#bbb;font-size:12px}
`;

function page(title: string, body: string): string {
  return `<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>${CSS}</style></head><body>${body}<footer>agentergonomics.org · AX = Agent Experience · generated by the <a href="https://github.com/shinyobjectz/agent-ergonomics">agent-ergonomics</a> skill</footer></body></html>`;
}

function reportPage(entry: any, profile: Profile, fixes: any[]): string {
  const byCell = new Map(profile.cells.map((c: any) => [cellId(c.surface, c.lens), c]));
  const head = "<tr><th>Surface ↓ / Lens →</th>" + LENSES.map((l) => `<th class=tiny>${esc(LENS_LABEL[l])}</th>`).join("") + "</tr>";
  const rows = SURFACES.map((s) => {
    const tds = LENSES.map((l) => {
      const c: any = byCell.get(cellId(s, l));
      const v = c ? c.normalized : null;
      return `<td class=n><span class=cell style="${cellStyle(v)}">${fmt(v)}</span></td>`;
    }).join("");
    return `<tr><td><b>${esc(SURFACE_LABEL[s])}</b></td>${tds}</tr>`;
  }).join("");
  const flags = profile.hostileFlags.length
    ? `<h2>Agent-hostile cells</h2><ul>${profile.hostileFlags.map((f: any) => `<li><span class=flag>${esc(f.cell)}</span> — ${esc(f.why)}</li>`).join("")}</ul>`
    : `<p class=muted>No agent-hostile cells at this tier.</p>`;
  const fixList = fixes.length
    ? `<h2>Prioritized fixes</h2><ol>${fixes.map((f) => `<li><b>${esc(f.title)}</b> <span class=tiny>${esc(f.cell)}</span><br><span class=muted>${esc(f.rationale)}</span>${f.patch ? `<pre class=tiny style="background:#fafafa;padding:8px;border-radius:6px;overflow:auto">${esc(f.patch)}</pre>` : ""}</li>`).join("")}</ol>`
    : "";
  return page(`${entry.id} — AX`, `
    <p class=tiny><a href="../index.html">← all benchmarks</a></p>
    <h1>${esc(entry.id)}</h1>
    <p class=sub>kind: ${esc(entry.kind)} · category: ${esc(entry.category)} · tier: ${esc(profile.tier)} · overall ${fmt(entry.overall)} · autonomy ${fmt(entry.autonomy)}</p>
    <h2>Matrix</h2>
    <table>${head}${rows}</table>
    <p class=tiny>Cells are instrument readings in −1…+1 (hostile is negative), not 1–5 scores. Human surface is unmeasured at Screen tier.</p>
    ${flags}
    ${fixList}`);
}

export async function buildSite(outDir: string): Promise<{ count: number }> {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(join(outDir, "report"), { recursive: true });

  const keys = readdirSync(join(OOTA, "wrappers")).filter((f) => f.endsWith(".work")).map((f) => f.replace(/\.work$/, "")).sort();
  const subjects: any[] = [];
  for (const key of keys) {
    try {
      const p = await screen(`oota:${key}`);
      const overall = (() => {
        const xs = Object.values(p.rollups.perSurface).filter((v): v is number => v !== null);
        return xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null;
      })();
      const entry = {
        id: `oota:${key}`,
        kind: "tool",
        category: key.split("-")[0],
        overall,
        autonomy: p.rollups.autonomy,
        hostile: p.hostileFlags.length,
        perSurface: p.rollups.perSurface,
        report: `report/${safe("oota:" + key)}.html`,
      };
      subjects.push(entry);
      writeFileSync(join(outDir, entry.report), reportPage(entry, p, designFixes(p)));
    } catch {}
  }

  // benchmark DB
  writeFileSync(join(outDir, "benchmark.json"), JSON.stringify({ generated: "static", subjects }, null, 2));

  // index — tabs by kind, table, inline data, tiny filter/sort JS
  const counts = KINDS.map((k) => ({ ...k, n: subjects.filter((s) => s.kind === k.id).length }));
  const tabs = `<div class=tabs id=tabs><span class="tab on" data-k=all>All<span class=n>${subjects.length}</span></span>` +
    counts.map((k) => `<span class=tab data-k=${k.id}>${esc(k.label)}<span class=n>${k.n}</span></span>`).join("") + "</div>";
  const rows = subjects.map((s) =>
    `<tr data-kind=${s.kind} data-cat=${esc(s.category)} data-q="${esc(s.id)}">
      <td><a href="${esc(s.report)}">${esc(s.id)}</a></td>
      <td class=muted>${esc(s.category)}</td>
      <td class=n><span class=cell style="${cellStyle(s.overall)}">${fmt(s.overall)}</span></td>
      <td class=n>${fmt(s.autonomy)}</td>
      <td class=n>${s.hostile ? `<span class=flag>${s.hostile}</span>` : "0"}</td>
      ${SURFACES.map((su) => `<td class=n><span class=cell style="${cellStyle(s.perSurface[su] ?? null)}">${fmt(s.perSurface[su] ?? null)}</span></td>`).join("")}
    </tr>`).join("");
  const th = `<tr><th data-s=id>Subject</th><th data-s=cat>Category</th><th data-s=overall>Overall</th><th data-s=autonomy>Autonomy</th><th data-s=hostile>Hostile</th>${SURFACES.map((s) => `<th class=tiny>${SURFACE_LABEL[s][0]}</th>`).join("")}</tr>`;

  const js = `
  const tabs=document.getElementById('tabs'), q=document.getElementById('q'), rows=[...document.querySelectorAll('tbody tr')];
  let kind='all';
  function apply(){const t=(q.value||'').toLowerCase();for(const r of rows){const ok=(kind==='all'||r.dataset.kind===kind)&&r.dataset.q.toLowerCase().includes(t);r.style.display=ok?'':'none';}}
  tabs.addEventListener('click',e=>{const t=e.target.closest('.tab');if(!t)return;kind=t.dataset.k;[...tabs.children].forEach(c=>c.classList.toggle('on',c===t));apply();});
  q.addEventListener('input',apply);
  document.querySelectorAll('th[data-s]').forEach(h=>h.addEventListener('click',()=>{
    const key=h.dataset.s, tb=document.querySelector('tbody');
    const get=r=>{const c=r.querySelector(key==='id'?'td a':key==='cat'?'td:nth-child(2)':key==='overall'?'td:nth-child(3)':key==='autonomy'?'td:nth-child(4)':'td:nth-child(5)');const v=c?c.textContent.trim():'';const n=parseFloat(v);return isNaN(n)?v:n;};
    const sorted=[...rows].sort((a,b)=>{const x=get(a),y=get(b);return typeof x==='number'?x-y:String(x).localeCompare(y);});
    if(h.dataset.dir==='asc'){sorted.reverse();h.dataset.dir='desc';}else h.dataset.dir='asc';
    sorted.forEach(r=>tb.appendChild(r));
  }));`;

  const body = `
    <h1>Agent Ergonomics</h1>
    <p class=sub><b>AX = Agent Experience.</b> How well a tool, SDK, skill, harness, or system serves an <i>average</i> agent — measured first-principles across a surfaces×lenses matrix. ${subjects.length} subjects benchmarked.</p>
    ${tabs}
    <input id=q class=q placeholder="filter subjects…">
    <table><thead>${th}</thead><tbody>${rows}</tbody></table>
    <p class=tiny>Columns D/I/L/R/H = Disclosure · Interface · Loop · Recursion · Human (per-surface mean, −1…+1). Click a header to sort; click a subject for its full report. <a href="benchmark.json">benchmark.json</a></p>
    <script>${js}</script>`;
  writeFileSync(join(outDir, "index.html"), page("Agent Ergonomics — agentergonomics.org", body));

  // Cloudflare Pages bits
  writeFileSync(join(outDir, "_headers"), "/*\n  Cache-Control: public, max-age=300\n");
  writeFileSync(join(outDir, "README.md"), "# agentergonomics.org (static)\n\nGenerated by `ax site`. Deploy on **Cloudflare Pages** with build output dir = `site/` (no build command — static). Re-run `ax site` to publish new results.\n");

  return { count: subjects.length };
}
